messaging:
  from:
    activemq:
      host: localhost
      port: 5672
      # Comma separated address. The format is host1:port1,host2:port2
      addresses: ${messaging.from.activemq.host}:${messaging.from.activemq.port}
      url: amqp://${messaging.from.activemq.addresses}
      fromRoute:
        topicName: alfresco.events.source
        # Available connections: amqpFromConnection|amqpFromCachedConnection
        # Use amqpFromConnection for durable topic subscription and amqpFromCachedConnection for everything else (E.g. Virtual Topics)
        uri: amqpFromConnection:topic:${messaging.from.activemq.fromRoute.topicName}?clientId=cae3bae3-event-gateway&durableSubscriptionName=event-gateway


  to:
    activemq:
      host: localhost
      port: 5672
      # Comma separated address. The format is host1:port1,host2:port2
      addresses: ${messaging.to.activemq.host}:${messaging.to.activemq.port}
      url: amqp://${messaging.to.activemq.addresses}
      toRoute:
        topicName: alfresco.events.allEvents
        # Only available connection: amqpToCachedConnection
        uri: amqpToCachedConnection:topic:${messaging.to.activemq.toRoute.topicName}
